# Test Application Configuration
server.port=8080

# BoxLang templating configuration
# The auto-configuration will pick up classpath:/boxlang.json automatically.
# Override only as needed.
#boxlang.config-path=/path/to/custom/boxlang.json
boxlang.prefix=classpath:/templates/
boxlang.suffix=.bxm

# Logging
logging.level.ortus.boxlang=DEBUG
logging.level.org.springframework.web=INFO
